[build]
  publish = "public/"
  command = "npm run build"
  SUPABASE_URL = "env(SUPABASE_URL)"
  SUPABASE_KEY = "env(SUPABASE_KEY)" 

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.images]
  compress = true
[build.processing.html]
  pretty_urls = false

